date.format: "YYYY-MM-DD"
server: 
  port: 8082
spring:
  application:
    name: employee-service
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:employeedb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
